# Application / App / Microservice
application: 

 applicationName: "review"

 namespace:
    enabled: true
    additionalLabels:
      kind: pr
      team: gabbar
      stakater.com/tenant: gabbar

 route:
    enabled: true
    port:
      targetPort: https

 configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        DB_NAME: "nordmartDB"
        MONGO_HOST: "review-mongodb"

 deployment:
   additionalLabels:
     appCategory: "backend"
   annotations:
   volumes: {}
   imagePullSecrets: nexus-docker-config-forked
   envFrom:
    - type: configmap
      name: ""    
   image:
     repository: stakater/stakater-nordmart-review
     tag: v0.0.2
   resources: 
     limits:
       memory: 1Gi 
       cpu: 0.5
     requests:
       memory: 128Mi
       cpu: 0.1

   probes:
     readinessProbe:
       failureThreshold: 3
       periodSeconds: 60
       successThreshold: 1
       timeoutSeconds: 1
       initialDelaySeconds: 10
       httpGet:
         path: /actuator/health/readiness
         port: 8080
     livenessProbe:
       failureThreshold: 3
       periodSeconds: 60
       successThreshold: 1
       timeoutSeconds: 1
       initialDelaySeconds: 10
       httpGet:
         path: /actuator/health/readiness
         port: 8080

 service:
   ports:
   - port: 8080
     name: https
     targetPort: 8080

 rbac:
   create: true
   serviceAccount:
     create: true
     enabled: true

# MongoDB dependency
mongodb:

  fullnameOverride: review-mongodb  

  auth:
    enabled: false

  podSecurityContext:
    enabled: false

  containerSecurityContext:
    enabled: false
